// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVM-93WhBoAK2ZdMhHzR7qnkhCz-YosWI',
    appId: '1:150567634262:web:d5761908b58e31fa1842f7',
    messagingSenderId: '150567634262',
    projectId: 'arishti-assingm',
    authDomain: 'arishti-assingm.firebaseapp.com',
    storageBucket: 'arishti-assingm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPMQR1-9GwwucTo0ptn5RNnx9DjUuE-Uc',
    appId: '1:150567634262:android:efab132499c7c9531842f7',
    messagingSenderId: '150567634262',
    projectId: 'arishti-assingm',
    storageBucket: 'arishti-assingm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4DlJDD2Keac6QFXUZG9CgLQjE5W65Dy4',
    appId: '1:150567634262:ios:28adfbe1950e6e3a1842f7',
    messagingSenderId: '150567634262',
    projectId: 'arishti-assingm',
    storageBucket: 'arishti-assingm.appspot.com',
    iosClientId: '150567634262-e3v3vi8kvd62suahkc8fbav8go7s8tc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.arishtiAssignmentFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4DlJDD2Keac6QFXUZG9CgLQjE5W65Dy4',
    appId: '1:150567634262:ios:28adfbe1950e6e3a1842f7',
    messagingSenderId: '150567634262',
    projectId: 'arishti-assingm',
    storageBucket: 'arishti-assingm.appspot.com',
    iosClientId: '150567634262-e3v3vi8kvd62suahkc8fbav8go7s8tc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.arishtiAssignmentFlutter',
  );
}
